FROM node:18-alpine

WORKDIR /app

COPY backend/package.json ./package.json
COPY backend/package-lock.json ./package-lock.json

RUN npm install

COPY ./backend ./

CMD ["node", "server.js"]

EXPOSE 3000